"""Task 2.8: the catalog is the labeling function, and it is DATA (SPEC.md §4).

The task's done-when is byte-identity: the Phase-1 fixtures must produce exactly
the findings they produced under the hardcoded 1.4 table, with the labels now
served from `catalogs/exfil_v1.yaml`. `fixtures/golden/` holds those bytes —
generated by the OLD table, before the swap — so "nothing changed" is checked, not
claimed.

The rest of this module pins the properties that make the catalog a *tunable
layer* rather than a config file: it covers the real MCP stack, it can be
overlaid, and it fails loudly on a malformed entry.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from trifecta_lens.catalog import (
    Catalog,
    InvalidCatalogError,
    default_catalog,
    parse_catalog,
)
from trifecta_lens.engine import (
    FAMILY_TRIFECTA,
    FAMILY_TWO_LEG,
    detect_realized,
    satisfied_families,
)
from trifecta_lens.labeling import label_events
from trifecta_lens.loader import load_otlp_trace, load_trace
from trifecta_lens.roles import (
    SENSITIVE_DATA,
    SINK_EXFIL,
    SINK_IMPACT,
    UNTRUSTED_SOURCE,
)

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "fixtures"
GOLDEN = FIXTURES / "golden"
OTLP_TRACE = FIXTURES / "demo_mcp_trace.otlp.json"


# --- The done-when: a pure swap ---------------------------------------------


@pytest.mark.parametrize(
    "fixture", sorted(FIXTURES.glob("*.jsonl")), ids=lambda p: p.name
)
def test_catalog_labels_reproduce_the_hardcoded_findings_byte_for_byte(
    fixture: Path,
) -> None:
    """2.8's done-when. The golden bytes came from the pre-catalog table."""
    events = label_events(load_trace(fixture))
    produced = "".join(f.to_json_line() + "\n" for f in detect_realized(events))

    golden = GOLDEN / f"{fixture.stem}.findings.ndjson"
    assert golden.exists(), f"no golden for {fixture.name} — run `make golden`"
    assert produced == golden.read_text(encoding="utf-8"), (
        f"{fixture.name}: the catalog changed the findings. 2.8 is a SWAP: the "
        "labels move from code to data, the output does not move at all."
    )


# --- The carry-over: the catalog must fire on the REAL MCP trace -------------


def test_the_real_mcp_trace_fires_through_the_default_catalog() -> None:
    """The Phase-1 table knew `vault`/`webhook`. A real MCP trace names neither.

    This is what the catalog is *for*: the real Checkpoint D capture calls
    `filesystem__read_text_file` and `notify__send` (server-qualified, SPEC.md §2),
    and the shipped catalog covers them — so the UNCHANGED engine fires on a real
    trace with no code change anywhere. That is the whole thesis of invariant 2.
    """
    events = label_events(load_otlp_trace(OTLP_TRACE))
    findings = list(detect_realized(events))

    assert len(findings) == 1
    finding = findings[0]
    # No untrusted-source leg was captured in this run, so it is the LESSER family.
    # The catalog must never be used to invent the missing leg (SPEC.md §3.1).
    assert finding.family == FAMILY_TWO_LEG
    assert finding.family != FAMILY_TRIFECTA
    assert finding.sink_tool == "notify__send"
    assert finding.legs_not_observed == (UNTRUSTED_SOURCE,)

    # And the finding cites the catalog's rationale for each leg it did observe.
    notes = {leg.role: leg.note for leg in finding.legs}
    assert "filesystem" in notes[SENSITIVE_DATA]
    assert notes[SINK_EXFIL]


def test_default_catalog_covers_both_name_spaces() -> None:
    catalog = default_catalog()
    # Bare names (the flat fixtures, and any host that does not qualify).
    vault = catalog.label("vault")[SENSITIVE_DATA]
    assert vault.note == "reads a credential from the secret store"
    assert vault.entry == "vault.secret"
    assert set(catalog.label("webhook")) == {SINK_EXFIL}
    assert set(catalog.label("fetch")) == {UNTRUSTED_SOURCE}

    # Server-qualified names (a real MCP stack).
    assert set(catalog.label("fetch__fetch")) == {UNTRUSTED_SOURCE}
    assert set(catalog.label("filesystem__read_text_file")) == {SENSITIVE_DATA}
    assert set(catalog.label("filesystem__read_file")) == {SENSITIVE_DATA}
    assert set(catalog.label("filesystem__read_multiple_files")) == {SENSITIVE_DATA}
    assert set(catalog.label("notify__send")) == {SINK_EXFIL}

    # An unmatched tool gets NOTHING. Silence, never a guess.
    assert catalog.label("filesystem__list_directory") == {}
    assert catalog.label("some__unknown_tool") == {}
    assert catalog.label(None) == {}


def test_impact_sinks_are_catalogued_but_no_v1_family_accepts_on_them() -> None:
    """Coverage lives in the data; acceptance lives in the fixed machine.

    `filesystem__write_file` is a real impact sink and the catalog says so. The
    action-hijack family is fast-follow (SPEC.md §3), so v1 emits nothing for it —
    adding the entry changed no finding. That asymmetry IS the architecture.
    """
    assert set(default_catalog().label("filesystem__write_file")) == {SINK_IMPACT}


# --- The tunable layer ------------------------------------------------------


def test_overlay_adds_coverage_without_touching_code() -> None:
    """The user's extension point: 'my jira_read is an untrusted_source'."""
    overlay = parse_catalog(
        """
        version: 1
        entries:
          - id: mine.jira
            match: {tool: "jira__read_issue"}
            role: untrusted_source
            note: "issue text is written by third parties"
        """,
        source="<overlay>",
    )
    catalog = default_catalog().overlaid_with(overlay)

    assert set(catalog.label("jira__read_issue")) == {UNTRUSTED_SOURCE}
    # ...and the defaults still stand.
    assert set(catalog.label("notify__send")) == {SINK_EXFIL}


def test_overlay_wins_the_note_for_a_role_it_shares() -> None:
    overlay = parse_catalog(
        """
        version: 1
        entries:
          - id: mine.vault
            match: {tool: "vault"}
            role: sensitive_data
            note: "our vault holds customer PII, not just credentials"
        """,
        source="<overlay>",
    )
    catalog = default_catalog().overlaid_with(overlay)
    label = catalog.label("vault")[SENSITIVE_DATA]
    assert label.note == "our vault holds customer PII, not just credentials"
    # ...and the finding will cite the USER's entry, not ours.
    assert label.entry == "mine.vault"


def test_a_tool_matching_several_entries_takes_the_union() -> None:
    catalog = parse_catalog(
        """
        version: 1
        entries:
          - id: a
            match: {tool: "shared__thing"}
            role: sensitive_data
            note: "reads private rows"
          - id: b
            match: {tool: "shared__.*"}
            role: sink
            subtype: exfil
            note: "also posts them outward"
        """,
        source="<t>",
    )
    assert set(catalog.label("shared__thing")) == {SENSITIVE_DATA, SINK_EXFIL}


def test_labeling_is_deterministic() -> None:
    a = label_events(load_trace(FIXTURES / "demo_realized.jsonl"))
    b = label_events(load_trace(FIXTURES / "demo_realized.jsonl"))
    assert [e.to_dict() for e in a] == [e.to_dict() for e in b]


# --- Fail loudly ------------------------------------------------------------


def _entries(*bodies: str) -> str:
    return "version: 1\nentries:\n" + "".join(f"  - {{{b}}}\n" for b in bodies)


#: Every way an entry can be wrong. A mislabeled stack is worse than an unlabeled
#: one — it produces confident findings about roles nobody assigned — so each of
#: these must RAISE, never be skipped with a shrug.
MALFORMED = {
    "not a mapping": "not a mapping",
    "no entries list": "version: 1",
    "missing note (a finding must cite a rationale)": _entries(
        'id: a, match: {tool: "x"}, role: sink, subtype: exfil'
    ),
    "missing id (the id is the citation)": _entries(
        'match: {tool: "x"}, role: sensitive_data, note: n'
    ),
    "sink with no subtype": _entries('id: a, match: {tool: "x"}, role: sink, note: n'),
    "unknown role (a dropped role is a missing leg)": _entries(
        'id: a, match: {tool: "x"}, role: wat, note: n'
    ),
    "non-sink role carrying a subtype": _entries(
        'id: a, match: {tool: "x"}, role: sensitive_data, subtype: exfil, note: n'
    ),
    "match.tool is not a valid regex": _entries(
        'id: a, match: {tool: "[unclosed"}, role: sensitive_data, note: n'
    ),
    "duplicate entry ids": _entries(
        'id: a, match: {tool: "x"}, role: sensitive_data, note: n',
        'id: a, match: {tool: "y"}, role: sensitive_data, note: n',
    ),
}


@pytest.mark.parametrize("text", MALFORMED.values(), ids=MALFORMED.keys())
def test_malformed_catalog_fails_loudly(text: str) -> None:
    with pytest.raises(InvalidCatalogError):
        parse_catalog(text, source="<bad>")


def test_tag_matching_is_refused_not_silently_ignored() -> None:
    """v1 has no tags. Accepting the key and ignoring it would silently drop a rule."""
    with pytest.raises(InvalidCatalogError, match="NOT implemented"):
        parse_catalog(
            _entries('id: a, match: {tag: "secret"}, role: sensitive_data, note: n'),
            source="<bad>",
        )


def test_the_shipped_catalog_is_valid_and_every_entry_is_justified() -> None:
    catalog = default_catalog()
    assert isinstance(catalog, Catalog)
    assert catalog.entries
    for entry in catalog.entries:
        assert entry.note.strip(), f"{entry.id} ships without a rationale"
        assert entry.id.strip()


# --- Task 2.13's done-when --------------------------------------------------


def test_A_STRANGERS_SERVER_IS_COVERED_BY_EDITING_DATA_NOT_CODE() -> None:
    """2.13's done-when, executable.

    A stack this project has never heard of — a CRM server that reads customer rows
    and an internal wiki that publishes pages. Zero code knows those names. Under the
    shipped catalog they are invisible: unlabeled tools get no roles and the machine
    is silent, correctly.

    Adding ONE overlay file — no code, no engine change, no new branch — makes the
    same unmodified machine detect the full trifecta on that stack. That is the whole
    architectural claim of `CLAUDE.md` invariant 2, tested rather than asserted.
    """
    strangers_stack = frozenset(
        {"crm__read_customer_rows", "wiki__publish_page", "fetch__fetch"}
    )

    shipped = default_catalog()
    before = {t: set(shipped.label(t)) for t in strangers_stack}
    assert before["crm__read_customer_rows"] == set()  # invisible...
    assert before["wiki__publish_page"] == set()  # ...and silent about it.

    # The entire contribution: data.
    overlay = parse_catalog(
        """
        version: 1
        entries:
          - id: acme.crm.rows
            match: {tool: "crm__read_customer_rows"}
            role: sensitive_data
            note: "returns customer PII rows from our CRM"
          - id: acme.wiki.publish
            match: {tool: "wiki__publish_page"}
            role: sink
            subtype: exfil
            note: "publishes a page to the company-wide wiki, readable by everyone"
        """,
        source="<acme-overlay>",
    )
    extended = shipped.overlaid_with(overlay)

    roles = frozenset().union(*(extended.label(t) for t in strangers_stack))
    accepted = satisfied_families(roles)

    assert accepted, "the overlay did not make the stranger's stack detectable"
    assert accepted[0].id == FAMILY_TRIFECTA
    # And the engine never learned a thing about CRMs or wikis.


def test_the_catalog_covers_every_server_the_real_capture_used() -> None:
    """2.13: 'catalog entries for the servers the capture actually used'.

    Read off the REAL captured inventory, not a list we maintain by hand — so a
    future capture that adds a server cannot quietly go uncovered.
    """
    from trifecta_lens.inventory import load_inventory

    inventory = load_inventory(FIXTURES / "inventory.json")
    catalog = default_catalog()

    servers_with_a_role = {
        tool.server
        for context in inventory.contexts
        for tool in context.tools
        if catalog.label(tool.qualified)
    }
    assert servers_with_a_role == {"fetch", "filesystem", "notify"}


def test_the_docs_and_the_shipped_catalog_do_not_drift() -> None:
    """SPEC §4 summarizes the catalog. A summary nobody checks becomes a lie.

    Not a spell-check: it pins the two claims a reader would actually rely on — that
    every role in the alphabet is covered by at least one shipped entry, and that
    what SPEC calls out as deliberately ABSENT really is absent.
    """
    catalog = default_catalog()
    shipped_roles = {entry.role for entry in catalog.entries}
    assert shipped_roles == {SENSITIVE_DATA, SINK_EXFIL, SINK_IMPACT, UNTRUSTED_SOURCE}

    # SPEC §4 says these are deliberately NOT labeled, and says why. Hold it to that:
    # they return NAMES, not content, and labeling them would make every `ls` a leg.
    for name_only in (
        "filesystem__list_directory",
        "filesystem__search_files",
        "filesystem__get_file_info",
        "filesystem__directory_tree",
    ):
        assert catalog.label(name_only) == {}, (
            f"{name_only} returns names, not content — labeling it sensitive_data "
            "would make every directory listing a leg of an exfil finding."
        )

    spec = (ROOT / "SPEC.md").read_text(encoding="utf-8")
    assert "catalogs/exfil_v1.yaml" in spec
    assert "CONTRIBUTING.md" in spec


def test_every_finding_names_the_entry_that_assigned_each_role() -> None:
    """SPEC.md §4: a finding cites the entry, not just the rationale.

    The note tells a user what call we made; the ENTRY ID tells them what to edit.
    Without it, disagreeing with a label means reading our source — which is exactly
    the loop the catalog exists to close.
    """
    events = label_events(load_otlp_trace(OTLP_TRACE))
    finding = next(iter(detect_realized(events)))

    entries = {leg.role: leg.catalog_entry for leg in finding.legs}
    assert entries[SENSITIVE_DATA] == "mcp.filesystem.content_read"
    assert entries[SINK_EXFIL] == "mcp.notify.send"

    # And the cited ids are real entries a user can actually find and edit.
    shipped = {e.id for e in default_catalog().entries}
    assert set(entries.values()) <= shipped
